In [3]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

In [4]:
X = tf.placeholder(tf.float32, shape = [None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, W) + b

In [5]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train  = optimizer.minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
    cost_val, hy_val, _= sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print (step, "Cost : ", cost_val, "\nPrediction :\n", hy_val)

0 Cost :  12242.166 
Prediction :
 [[65.28575 ]
 [59.136124]
 [68.67094 ]
 [69.94671 ]
 [44.193237]]
10 Cost :  55.51358 
Prediction :
 [[162.91188]
 [176.52971]
 [184.31258]
 [195.88142]
 [133.74527]]
20 Cost :  55.11228 
Prediction :
 [[163.17862]
 [176.90445]
 [184.6536 ]
 [196.25668]
 [134.04135]]
30 Cost :  54.824207 
Prediction :
 [[163.15088]
 [176.9251 ]
 [184.6458 ]
 [196.25203]
 [134.06729]]
40 Cost :  54.53767 
Prediction :
 [[163.12234]
 [176.94463]
 [184.63698]
 [196.24632]
 [134.09238]]
50 Cost :  54.252625 
Prediction :
 [[163.09386]
 [176.96408]
 [184.62817]
 [196.24059]
 [134.11739]]
60 Cost :  53.969124 
Prediction :
 [[163.06544]
 [176.98347]
 [184.61937]
 [196.23482]
 [134.14232]]
70 Cost :  53.687122 
Prediction :
 [[163.03712]
 [177.00285]
 [184.61061]
 [196.22911]
 [134.16719]]
80 Cost :  53.40669 
Prediction :
 [[163.00887]
 [177.02214]
 [184.60188]
 [196.22346]
 [134.192  ]]
90 Cost :  53.12783 
Prediction :
 [[162.98068]
 [177.04137]
 [184.59315]
 [196.21774]


860 Cost :  35.605133 
Prediction :
 [[161.02322]
 [178.37846]
 [183.98714]
 [195.82756]
 [135.93079]]
870 Cost :  35.42209 
Prediction :
 [[161.00034]
 [178.39404]
 [183.98004]
 [195.823  ]
 [135.95073]]
880 Cost :  35.24005 
Prediction :
 [[160.97757]
 [178.40964]
 [183.97298]
 [195.81854]
 [135.97064]]
890 Cost :  35.05892 
Prediction :
 [[160.95482]
 [178.42516]
 [183.96594]
 [195.81404]
 [135.99051]]
900 Cost :  34.8789 
Prediction :
 [[160.93214]
 [178.44063]
 [183.95894]
 [195.80962]
 [136.0103 ]]
910 Cost :  34.69982 
Prediction :
 [[160.90955]
 [178.45607]
 [183.9519 ]
 [195.80513]
 [136.03003]]
920 Cost :  34.521706 
Prediction :
 [[160.887  ]
 [178.47147]
 [183.94493]
 [195.80072]
 [136.04971]]
930 Cost :  34.344444 
Prediction :
 [[160.8645 ]
 [178.48683]
 [183.93794]
 [195.79628]
 [136.06935]]
940 Cost :  34.16826 
Prediction :
 [[160.84206]
 [178.50212]
 [183.93098]
 [195.79187]
 [136.08891]]
950 Cost :  33.992935 
Prediction :
 [[160.81969]
 [178.51741]
 [183.92406]
 [19

1670 Cost :  23.561876 
Prediction :
 [[159.3565 ]
 [179.51599]
 [183.47   ]
 [195.5032 ]
 [137.38165]]
1680 Cost :  23.443584 
Prediction :
 [[159.33812]
 [179.52856]
 [183.4643 ]
 [195.4997 ]
 [137.39764]]
1690 Cost :  23.32597 
Prediction :
 [[159.31976]
 [179.54109]
 [183.4586 ]
 [195.49615]
 [137.41356]]
1700 Cost :  23.209028 
Prediction :
 [[159.30147]
 [179.55357]
 [183.45291]
 [195.49263]
 [137.42943]]
1710 Cost :  23.092625 
Prediction :
 [[159.2832 ]
 [179.56601]
 [183.44724]
 [195.48918]
 [137.44528]]
1720 Cost :  22.976841 
Prediction :
 [[159.26497]
 [179.57843]
 [183.44154]
 [195.48567]
 [137.46103]]
1730 Cost :  22.86174 
Prediction :
 [[159.24683]
 [179.59084]
 [183.43593]
 [195.4822 ]
 [137.47679]]
1740 Cost :  22.747284 
Prediction :
 [[159.22873]
 [179.6032 ]
 [183.43031]
 [195.47873]
 [137.4925 ]]
1750 Cost :  22.633427 
Prediction :
 [[159.21066]
 [179.61551]
 [183.42471]
 [195.47528]
 [137.50815]]
1760 Cost :  22.5201 
Prediction :
 [[159.19264]
 [179.62779]
 [18