In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

In [12]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b

In [13]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [14]:
for step in range(2001):
    cost_val, hy_val, _= sess.run([cost, hypothesis, train],
                                 feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost : ", cost_val, "\nPrediction : \n", hy_val)

0 Cost :  40696.375 
Prediction : 
 [-24.81732  -32.429523 -30.655134 -33.08899  -25.584507]
10 Cost :  5.74169 
Prediction : 
 [153.61911 182.05374 180.67061 197.04008 138.01566]
20 Cost :  5.342853 
Prediction : 
 [154.1506  182.70847 181.30746 197.73424 138.51848]
30 Cost :  5.316642 
Prediction : 
 [154.14384 182.71623 181.30687 197.73424 138.52782]
40 Cost :  5.2905493 
Prediction : 
 [154.13547 182.722   181.30432 197.73212 138.53564]
50 Cost :  5.2646303 
Prediction : 
 [154.1271  182.72775 181.30182 197.73001 138.54344]
60 Cost :  5.238824 
Prediction : 
 [154.11877 182.73349 181.2993  197.72789 138.55122]
70 Cost :  5.2131515 
Prediction : 
 [154.11047 182.73923 181.2968  197.72578 138.55899]
80 Cost :  5.187631 
Prediction : 
 [154.10217 182.74493 181.29428 197.72368 138.56671]
90 Cost :  5.162257 
Prediction : 
 [154.09392 182.75063 181.2918  197.72159 138.57443]
100 Cost :  5.136992 
Prediction : 
 [154.08568 182.7563  181.28929 197.7195  138.58214]
110 Cost :  5.1118774 
P

990 Cost :  3.3561585 
Prediction : 
 [153.43602 183.20424 181.09349 197.55246 139.19144]
1000 Cost :  3.3405616 
Prediction : 
 [153.4296  183.20871 181.09158 197.55078 139.19753]
1010 Cost :  3.325072 
Prediction : 
 [153.42317 183.21312 181.08963 197.54909 139.20357]
1020 Cost :  3.3096728 
Prediction : 
 [153.41676 183.21753 181.0877  197.54741 139.2096 ]
1030 Cost :  3.2943738 
Prediction : 
 [153.4104  183.22194 181.0858  197.54575 139.2156 ]
1040 Cost :  3.279143 
Prediction : 
 [153.40404 183.22633 181.0839  197.54408 139.2216 ]
1050 Cost :  3.2639854 
Prediction : 
 [153.39767 183.2307  181.08197 197.54242 139.22758]
1060 Cost :  3.248906 
Prediction : 
 [153.39136 183.23508 181.08008 197.54077 139.23357]
1070 Cost :  3.233942 
Prediction : 
 [153.38506 183.23941 181.07817 197.53911 139.2395 ]
1080 Cost :  3.2190185 
Prediction : 
 [153.37875 183.24374 181.07626 197.53745 139.24544]
1090 Cost :  3.204197 
Prediction : 
 [153.3725  183.2481  181.0744  197.53583 139.25137]
1100 

1900 Cost :  2.2322512 
Prediction : 
 [152.91777 183.5621  180.93796 197.41455 139.68253]
1910 Cost :  2.222692 
Prediction : 
 [152.91277 183.56555 180.93646 197.41318 139.68729]
1920 Cost :  2.213169 
Prediction : 
 [152.90779 183.56902 180.93497 197.41182 139.69205]
1930 Cost :  2.2037117 
Prediction : 
 [152.9028  183.57245 180.93347 197.41046 139.69678]
1940 Cost :  2.194308 
Prediction : 
 [152.89784 183.57585 180.93199 197.40912 139.70152]
1950 Cost :  2.184943 
Prediction : 
 [152.89291 183.5793  180.93053 197.40779 139.70625]
1960 Cost :  2.1756425 
Prediction : 
 [152.88797 183.5827  180.92905 197.40643 139.71094]
1970 Cost :  2.1663976 
Prediction : 
 [152.88304 183.58609 180.92757 197.4051  139.71562]
1980 Cost :  2.157177 
Prediction : 
 [152.87814 183.58948 180.92612 197.40376 139.72032]
1990 Cost :  2.1479945 
Prediction : 
 [152.87326 183.59288 180.92465 197.40244 139.725  ]
2000 Cost :  2.1388848 
Prediction : 
 [152.86836 183.59624 180.92317 197.4011  139.72964]
