In [1]:
import numpy as np
import tensorflow as tf

In [2]:
xy = np.loadtxt('train.txt', unpack=True, dtype='float32')
x_data = xy[0: -1]
y_data = xy[-1]

In [3]:
print(x_data)

[[1. 1. 1. 1. 1.]
 [1. 0. 3. 0. 5.]
 [0. 2. 0. 4. 0.]]


In [4]:
print(y_data)

[1. 2. 3. 4. 5.]


In [5]:
W = tf.Variable(tf.random_uniform([1, len(x_data)], -5.0, 5.0))

# hypothesis
hypothesis = tf.matmul(W, x_data)

# cost func
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

In [6]:
# Minimize
a = tf.Variable(0.1) # learning rate
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# init
init = tf.global_variables_initializer()

# Launch
sess = tf.Session()
sess.run(init)

In [36]:
# Fitting
for step in range(2001):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(cost), sess.run(W))

0 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
20 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
40 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
60 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
80 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
100 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
120 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
140 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
160 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
180 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
200 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
220 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
240 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
260 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
280 1.7763568e-14 [[-2.9644815e-07  1.0000001e+00  1.0000001e+00]]
3